### ISSUE TITLE
Implement an exporter for excel file (csv?) that will be enabled by default with zero configuration needed

### ISSUE THREAD

**Issue by brafdlog** [brafdlog/budget-tracking#109]
All our current exporters require configuration (except for json that will probably not be useful for the common person).
Having a valuable exporter that works out of the box is important because it gives immediate value and will reduce the chance that people will give up during the initial setup to the complexity of it.
So, we can should create a new exporter that exports to an excel file (csv? xlsx?). This exporter will be enabled by default with some default file path.
On the ui of the excel exporter config there will be a link to open the file.

**Comment by brafdlog** [comment]
@baruchiro thoughts?

**Comment by baruchiro** [comment]
Sounds good, no questions. I also thought about export to some calculated excels like [אקסולידית](https://docs.google.com/spreadsheets/d/1bWIhiY4sfykoMSOeypKFTayon3ARkOju8qsJrsEdLdw) or [פעמונים](https://www.paamonim.org/wp-content/uploads/2020/04/%D7%A8%D7%99%D7%A9%D7%95%D7%9E%D7%99%D7%AA-%D7%91%D7%90%D7%A7%D7%A1%D7%9C-230420.xlsx)

**Comment by giladtaase** [comment]
I can take this

**Comment by giladtaase** [comment]
So excel or CSV? I'd say CSV because it give almost the same value for Excel users, but is also useful for other products.

**Comment by baruchiro** [comment]
Of course, you are right, the intention is CSV.

**Comment by giladtaase** [comment]
Ok I got the basics working but I have a few clarifications I need
1) Should we support merging of existing data like the JSON exporter does?
2) Do we want to put a header line with field names?
3) I just separated the values with commas, but then thought I'll need to escape them if the values themselves have commas, and found out there's no unique standard for this. Is there maybe a popular library that you know of, which will generate a more or less common CSV output?

**Comment by baruchiro** [comment]
1. I think so, let's keep it work in the same way.
2. You can either add a checkbox to the frontend to decide about the header line. If you don't want, I think we should use the header line. Worst case, even if we didn't use the checkbox, I hope most programs will accept this file have a checkbox for the input 😉
3. I used [`json2csv`](https://www.npmjs.com/package/json2csv) somewhere in other software
