### ISSUE TITLE
Handle cases of no exporters, importers or transactions

### ISSUE THREAD

**Issue by baruchiro** [brafdlog/budget-tracking#111]
- [ ] Are we should run if no importers defined? (For example, to test the exporters)
- [ ] Are we should export if no transactions fetched (empty array)?
- [ ] Are we should throw or ignore or event not start to import if no exporters?

**Comment by brafdlog** [comment]
- I don't think we should run without importers. It doesn't make much sense. Tests flows should probably mock the importers config and results.
- If there are no transactions there is nothing to export so I don't see why we should run the exporters.
- Running without exporters also doesn't make much sense. Long term I think we should have a wizard for empty state - initial setup. Short term, we can disable the run button with a tooltip explaining why. 

WDYT?

**Comment by baruchiro** [comment]
Fine, I opened this issue because currently, we don't handle these cases

**Comment by brafdlog** [comment]
This is a subset of the first time flow. Created an issue for that: #111

**Comment by baruchiro** [comment]
> This is a subset of the first time flow. Created an issue for that: #111

I don't think it exactly the same...

We still handle the case when the use (even accidentally) disabled all the exporters (or importers, if they can be enabled/disabled)

(BTW you referred to the current 111 issue.)
