### ISSUE TITLE
Exporting data to a Google Spreadsheet to allow automations

### ISSUE THREAD

**Issue by Moshet** [brafdlog/budget-tracking#116]
Exporting data to a Google Spreadsheet to allow automations - can be exported on demand (and be filtered by dates and/or cards/categories) AND on a regular basis, when new transaction appears. This will provide an opportunity for further automations, such as emails.

**Comment by baruchiro** [comment]
We are working to export to Google Spreadsheet in the new version on `unifyRepos` branch.

**Comment by brafdlog** [comment]
Closing this as there are already issues for it #84 #32
