### ISSUE TITLE
Make installation of app work on windows

### ISSUE THREAD

**Issue by giladtaase** [brafdlog/budget-tracking#131]
When I try to install by running israeli-bank-scrapers-desktop Setup 0.1.3-beta.exe of unifyRepos, either by building from code or by taking the artifacts from github, it gets stuck on "Installing, please wait".
I was not yet able to find where the log files are.

![image](https://user-images.githubusercontent.com/943999/101891583-e9ec7900-3baa-11eb-9ba6-d724c298616b.png)

**Comment by brafdlog** [comment]
@baruchiro I don't have a windows pc at the moment. Can you take a look?

**Comment by baruchiro** [comment]
I added to the board, to check that before the merge.

Otherwise I will take that some day in future

**Comment by baruchiro** [comment]
@brafdlog Do we want to test the Linux installation?

If so, please open another issue or just add to this.

Reference: https://github.com/baruchiro/israeli-bank-scrapers-desktop/issues/14

**Comment by giladtaase** [comment]
@baruchiro Are you working on this one? I can look into it if you give me some initial pointers (code location, enabling installation logs).

**Comment by baruchiro** [comment]
I'm not working on it right now.
I don't know how to debug it. You need to know that we are using `electronBuilder`, and its configuration is [here](https://github.com/brafdlog/budget-tracking/blob/bba24ee5c7b8cad41ae34b1a23f3a40b90208520/vue.config.js#L21-L62).

The [vue-cli-plugin-electron-builder](https://nklayman.github.io/vue-cli-plugin-electron-builder/) is taking these config and actually run the `electron-builder`.

Please make sure you are looking at the right version of `vue-cli-plugin-electron-builder`

**Comment by giladtaase** [comment]
Great thanks, I'll try to take it from here.

**Comment by baruchiro** [comment]
@giladtaase  You may assign yourself.

**Comment by giladtaase** [comment]
@baruchiro I'm not sure that I have permission to assign. At least, I can't find where to to do.
Why did you link to https://github.com/baruchiro/israeli-bank-scrapers-desktop/issues/99, do you think it's related? Or did you mean to link it to #152?

**Comment by baruchiro** [comment]
Maybe only collaborators can be assigned

**Comment by giladtaase** [comment]
You can certainly assign to me, I cannot assign to myself. Probably, any collaborators can assign anything.Anyone, I cannot reproduce the issue now. I'll try tomorrow on the same environment where I first reproduced it.

**Comment by baruchiro** [comment]
@giladtaase It working on my Windows without any problem.
