### ISSUE TITLE
When trying to setup google sheets in the installed application there is an error "No 'clientId' or 'clientSecret' for google login

### ISSUE THREAD

**Issue by brafdlog** [brafdlog/budget-tracking#150]
To reproduce:

- Download the build artifact for windows
- Install and run it
- Click on google sheets exporter config
- Click login to google

Expected result - being able to login to google and setup the google sheets integration

Actual - Getting an error of no 'clientId' or 'clientSecret' for google login

**Comment by baruchiro** [comment]
I left a comment somewhere that you need to configure those secrets in the Github Repository Secrets, according to the Github Actions.

If you need help I will help you later.

**Comment by brafdlog** [comment]
Added the secrets. Solved

**Comment by baruchiro** [comment]
@brafdlog There is another thing, also similar to #149. We need to do some configurations in the Google console to remove the warning about "Untrusted app" when logging in with google.

**Comment by brafdlog** [comment]
The changes i made in the last pr (reducing the scopes we use) should solve this
