### ISSUE TITLE
Yarn start doesn't work

### ISSUE THREAD

**Issue by dangourary** [brafdlog/budget-tracking#179]
`D:\Repos\budget-tracking>yarn start
yarn run v1.22.5
error Command "start" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by baruchiro** [comment]
Hi, welcome to the project!

Sorry, the `README.md` file is outdated, we are working on it in #177.

To run this project you need to first run `yarn` to install the dependencies, and then run `yarn serve` to run the app.

For the next time you get to a *JavaScript*/*TypeScript* project, you will know that you can look at a file called `package.json` and see what commands (scripts) exist:

https://github.com/brafdlog/budget-tracking/blob/c5a719c78af7c44c5cd340a1634da842497d1bf8/package.json#L11-L23

Please try to run, and for any other question, you can open another issue, or if you are not sure it is an issue or just a help request, you can open a new [discussion](https://github.com/brafdlog/budget-tracking/discussions/new)
