### ISSUE TITLE
CSV file export doesn't work

### ISSUE THREAD

**Issue by Moshet** [brafdlog/budget-tracking#181]
Is there a default directory in which it should be saved?
Entering my own directory didn't work.

**Comment by baruchiro** [comment]
Hi, can you please share the directory you entered?

Please just copy & paste the value from there to here, thanks!

**Comment by Moshet** [comment]
C:\Users\Dell\Downloads\transaction.csv

**Comment by baruchiro** [comment]
And what do you mean "didn't works"?

Are you getting an error message?

Is the scraping is done but you can't find the transaction file?

**Comment by Moshet** [comment]
No error message and no file, but scraping seems to be done successfully. Tried a few directories.
Also, the "default" directory looks like "..\transaction.csv" which is strange

**Comment by baruchiro** [comment]
I have to tell you that I have not yet run the software from the installable artifact, because I'm still working on solving its problems.
Next time I hope it will work and I will check this issue.

**Comment by baruchiro** [comment]
> No error message and no file, but scraping seems to be done successfully. Tried a few directories.
> Also, the "default" directory looks like "..\transaction.csv" which is strange

It will be like that until #155

**Comment by Moshet** [comment]
Just tried the up to date version:

1. There's no default directory at all now (shows only "transaction.csv"), but better than the previous "..\transaction.csv". Maybe better add a "browse" button?
2. When I paste a directory and click "save" - nothing happens ("save" is clicked but no file is saved in the directory)
3. What is the purpose of the "active" checkbox in the CSV file export menu? It didn't help with exporting the file

**Comment by baruchiro** [comment]
@Moshet Sorry for the very late answer. It was on my to-do list for a long time, but I need to answer you even if I don't have answers to all your questions.

1. Yes, we need to work on it, see #155.
2. I need to check this.
3. The purpose of "active" is to select, from all the exporters, which exporter you want to be used when you click on "Run".

**Comment by baruchiro** [comment]
@Moshet About paste a directory, we need to add validation. But I think the better is to focus on #155 to solve both.

**Comment by baruchiro** [comment]
About 2, trying to save to directory, for me it gives me an error.
Closing this issue, please let me know if there is something else.
