### ISSUE TITLE
Run error when following initial setup

### ISSUE THREAD

**Issue by guyklein** [brafdlog/budget-tracking#24]
After running the initial setup steps - I get a "Cannot find module './categoryCalculationScript'" error.
the "categoryCalculationScript.js" file is in the .gitignore. 
is it possible the categoryCalculationScript-example.js file was supposed to be part of the git repository but is not?

**Comment by brafdlog** [comment]
You should copy the `categoryCalculationScript-example.js` file to create a `categoryCalculationScript.js` file with your own category calculation logic. See the initial setup section in the README.

**Comment by guyklein** [comment]
Yeah... Saw it a minute too late :).
Thanks.
