### ISSUE TITLE
Authenticate with google sheets with oauth installed application flow instead of service flow

### ISSUE THREAD

**Issue by brafdlog** [brafdlog/budget-tracking#32]
The current authentication with google sheets is through a service account. 

This is far from ideal because it requires an annoying process and because it requires a scope (`auth/spreadsheets`) that grants much more access than what we actually need.

Instead we should implement the [oauth installed application flow](https://developers.google.com/identity/protocols/oauth2#installed) and probably use the `auth/drive.file` and create the spreadsheet from the app.

Also this should be exposed in the ui of the configuration so the user clicks a button to integrate google sheets and that starts the process.

**Comment by baruchiro** [comment]
@brafdlog Is is done, right?
