### ISSUE TITLE
Seperate the categories from the logic

### ISSUE THREAD

**Issue by baruchiro** [brafdlog/budget-tracking#46]
To avoid rename the `app/node/categoryCalculationScript-example.js` when starting to work with the project, and to prepare this project to be installable, we need first to get the categories mapping from an outer file.

In this way, we also can create a global configuration file that will hold many business names, and use it by default, unless the user want to derive or ignore it.

**Comment by brafdlog** [comment]
Thats true. There is an existing issue for that #31
