### ISSUE TITLE
Get financial list from 'israeli-bank-scrapers'

### ISSUE THREAD

**Issue by baruchiro** [brafdlog/budget-tracking#47]
The `FINANCIAL_COMPANIES_CONFIG` in `app/web/constants/financialCompaniesConfig.js` should be generated from the source list in the [`israeli-bank-scrapers`](https://github.com/eshaham/israeli-bank-scrapers/blob/master/src/definitions.js).

Now, if we want to enhance this list with logo and so on, we need to assign the additional info to the existed list, and handle default values when we did not configure our value yet.

In this way, you don't need to add configuration manually as #25 did.

**Comment by brafdlog** [comment]
Great idea

**Comment by brafdlog** [comment]
This can also be used for implementing the ui of the authentication fields for each account type dynamically

**Comment by brafdlog** [comment]
Irrelevant after merging israeli-bank-scrapers-desktop repo (#50)
