### ISSUE TITLE
The consistent naming convention in the repo is camelCase for directories and files

### ISSUE THREAD

**Issue by baruchiro** [brafdlog/budget-tracking#57]
The consistent naming convention in the repo is camelCase for directories and files so I would rename:

`config-manager` -> `configManager`
`default-config` -> `defaultConfig`

_Originally posted by @brafdlog in https://github.com/brafdlog/budget-tracking/pull/54#issuecomment-643321496_

I think the Vue part is not full compatible with this rule. But also need to think maybe in Vue the convention is different- https://vuejs.org/v2/style-guide/#Single-file-component-filename-casing-strongly-recommended

**Comment by brafdlog** [comment]
Thats true. Since they suggest either kebab-case or PascalCase for view components, and the rest of the code is camel case how about we use PascalCase for the components and camelCase for the rest?
