### ISSUE TITLE
Some cards don't use username field

### ISSUE THREAD

**Issue by antmir** [brafdlog/budget-tracking#61]
Isracard and amex use id and not username. so you have to manually add those configurations. also, because of the check in 
BankScraper.scrape (!credentials.username) user need to add a "dummy" username field as well

  id: <user identification number>,
  card6Digits: <6 last digits of card>
  password: <user password>

**Comment by brafdlog** [comment]
Welcome to the project :)

We are currently working on a major pr #50 that will merge the `israeli-bank-scrapers-desktop` repo into this project and will include significant changes to the ui including the handling of different credentials field per financial institution.

I will leave this issue open until that PR is merged.

In the mean time if you want to contribute I suggest creating prs based on the unifyRepos branch.

**Comment by baruchiro** [comment]
@antmir It is working now. I'm using Isracard and everything is good.
