### ISSUE TITLE
Update the readme and add to it the setup flow for the app from scratch

### ISSUE THREAD

**Issue by brafdlog** [brafdlog/budget-tracking#85]
- Update the readme
- Document in Readme the up to date flow of setting up the app from scratch with importers and exporters

**Comment by baruchiro** [comment]
> At the beginning of the `README`, we should clearly state the division of responsibilities between us and the Scrapers library.
> 
> As long as we don't do this, we will have to answer a lot of questions related to the Scrapers library (and even after we will do it ;-))
> 
> *From https://github.com/baruchiro/israeli-bank-scrapers-desktop/issues/50*

**Comment by baruchiro** [comment]
@brafdlog Closing this. When we will find something else to add to the README, we will just change it or open a new issue
